### ISSUE TITLE
Can't download SVG - Flowmaker in browser doesn't work

### ISSUE THREAD

**Issue by rgeraldporter** [aryaminus/flowmaker#2]
Hi - love this plugin. I just have no way of actually getting a hold of the SVG generated. There doesn't seem to be a save option in the editor, and the browser download just gives an error.

On the browser, it doesn't display the SVG, and only gives this when I download the SVG:
<img width="532" alt="screen shot 2018-01-11 at 12 02 55" src="https://user-images.githubusercontent.com/955052/34837044-9c105c2c-f6c7-11e7-9c91-55e115e0abf9.png">

**Comment by aryaminus** [comment]
Make sure express and socket.io is installed, else fall back to the version as in package.json. We are working on setting up download option in Editor

**Comment by psuzn** [comment]
We are using FileSaver.js to save the SVG which implements saveAs () FileSaver interface of html5 and data: URI or other methods in browsers that do not natively support it.So that might be the cause of the error.Could you tell which browser and version of that you are using?
