### ISSUE TITLE
command 'vscode.previewHtml' not found

### ISSUE THREAD

**Issue by atian25** [aryaminus/flowmaker#8]
https://github.com/Microsoft/vscode/issues/62630

**Comment by kostasx** [comment]
@aryaminus This is a known issue with the deprecated `previewHtml` which has been replaced by the [WebView API](https://code.visualstudio.com/api/extension-guides/webview). Here's some snippets from an extension I've updated lately that uses the WebView API to display the JS flowchart: [Create WebView](https://github.com/kostasx/live-html-preview-v2/blob/master/src/Utilities.ts#L67) / [Update WebView Content](https://github.com/kostasx/live-html-preview-v2/blob/master/src/Utilities.ts#L23). I hope this helps to update the Extension.

Meanwhile, @atian25, you can use [this extension](https://marketplace.visualstudio.com/items?itemName=kostasx.live-html-previewer-v2), as Flowchart is now supported for .js files

**Comment by Berkmann18** [comment]
This is still an issue which needs to be fixed in this plugin.
@aryaminus Can you please fix this.

**Comment by aryaminus** [comment]
Will fix it in a week's span if I get time. PRs appreciated
